# Homework 1
Complete the exercises working in your group. You may share the notebook with your group members using the share button in the upper right. Be careful with this feature. Although similar to Google Docs in functionality, you will notice that if two people are working on the same cell at the same time, then you may lose your work in that cell.

## Question 1
Who are you? Introduce yourself and your group members, using multiple markdown features such as embedded pictures, links to your linkedin or webpage, sections and subsections, and more.

_**FONTATA**_
<img src="fontana.jpg" alt="fontana" width="450"/>
Photo by [Vaishnav Chogale](https://unsplash.com/@vshnv_c?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText) on [Unsplash](https://unsplash.com/s/photos/fontana-pizza?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText)
* **Fanjiaxuan(Dylan) Zhang** 

    * I am a junior studying Applied Mathematics & Statistics (AMS) and Economics. Beacuse of Covid, I am currently back home in China and taking all my classes remotely.

* **Shirley Chen**

    * I am a junior majoring in QSS with computing informatics track and minoring in Environmental Science. I am now in Johns Creek, Georgia. 

* **Katherine Wang**

    * I am a junior studying AMS and Econ remotely in China, hoping we can get back to campus next semester.
* **Teresa Yu**

    * I am a junior majoring in QSS-Economics and minoring in Math. I am currently taking classes remotely as well.
* **Howard Hou**   
    * I am a junior majoring in AMS and minoring in CS. I am currently in China, and looking forward to going back to campus in the fall.

## Question 2
What is the smallest integer $x$ for which NumPy fails to compute 
$$ \log(e^x)= x$$

Explain in your own words, using links and citations if needed, why this happens.

### Example calculations
The largest number for which it fails is 710.

In [ ]:
import numpy as np

In [ ]:
np.log((np.e)**709)

709.0

In [ ]:
# fails
#np.log((np.e)**(710))

### Answer to Q2

In [ ]:
np.log((np.e)**-745)

-744.4400719213812

In [ ]:
np.log((np.e)**-746)

/shared-libs/python3.7/py-core/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.

-inf

The smallest integer $x$ for which NumPy fails to compute $ \log(e^x)= x$ is when $x = -746$. 

Python implements decimals with double-precision floating-point numbers, which would allow the representation of numbers between $10^{-308}$ to $10^{308}$, with full 15-17 decimal
 digits precision; a smaller value up to $5\times10^{-324}$ can also be achieved by compromsiing precision (ref: [IEEE 754](https://en.wikipedia.org/wiki/IEEE_754#2019), [Double-precision floating-point format](https://en.wikipedia.org/wiki/Double-precision_floating-point_format)). 
This would result in any floats outside of the range to either cause an overflow or underflow. While an underflow typically would result in a return of 0,
 overflow, on the other hand, causes an error: `OverflowError: (34, 'Numerical result out of range')`.

In [ ]:
print(np.e**709)
print(np.e**-746)

8.218407461554662e+307
0.0

In order for python to execute `np.log(np.e**x)`, `np.e**x` has to be computed first.

Based on the code above, $e^{709} \in (10^{-308},10^{308})$; however, if we increase the exponent by 1, $e^{710}\notin (10^{-308},10^{308})$, which is outside of the double-precision float range and therefore causing an overflow erorr. This
 makes the `np.log((np.e)**(710))` throw
  an error.

`np.log((np.e)**-746)` gives the result `-inf` because `np.e**-746` causes an underflow and reutruns 0. The function $\ln(x)$ is not defined at $x=0$, and $\lim\limits_{x\to 0^+} \ln{x} =-\infty$.

## Question 3
Recall in notebook 1, an exercise posed the following question.
> "Harvard's tuition in 1970 was \$4,070 (not including room, board, and fees). 
In 2019 it is \$46,340.  What was the annual rate of increase over that period, treating it as if it had compounded continuously?


Did Harvard's tuition have an higher annual rate of increase than other school's? In this question, your group needs to gather data on *five* other schools, compute the annual increase for them, and compare with Harvard's. Intermix with your code an interesting narrative that explains why you are interested in those five schools, what you expected to see in their rate of increase, and what is actually seen after making the calculations. Include links to any data sources you use, and pictures as well as other markdown features to make your response visually appealing.

Here are example calculations to get you started.

### Example calculations

Emory's tuition in 1970 was $1,980 (not including room, board, and fees) [[Not Your Motherâ€™s College
Affordability Crisis ](https://deltacostproject.org/sites/default/files/products/Delta-Cost-Not-Your-Moms-Crisis_0.pdf)].

In the 2020-2021 academic year, it is $53,070 [[Office of Undergraduate Admissions](https://apply.emory.edu/financial-aid/index.html)]. What was the annual rate of increase over that period, treating it as if it had compounded continuously?

Solving for $r$ in the equation
$$V = P e^{rt}$$
one finds
$$\frac{\log(V/P)}{t}= r$$

In [ ]:
P = 1980
V = 53070
t = 2020-1970

In [ ]:
r = np.log(V/P)/t
r

0.0657702990426672

In [ ]:
percent = r*100

In [ ]:
f"So the annual rate, compounded continuously, is {round(percent, 2)}%"

'So the annual rate, compounded continuously, is 6.58%'

### Answer to Q3

Our group chose the following 5 schools to analyze because they all have rich histories. We were expecting them to have simlar rate of increase but less than that of Harvard.
<img src="brick.jpg" alt="fontana" width="450"/>
<span>Photo by <a href="https://unsplash.com/@kismet?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Christopher</a> on <a href="https://unsplash.com/?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>

1. **College of William & Mary**'s [tuition in 1970](https://www.wm.edu/offices/financialoperations/sa/tuition/historical-tuition-data/history/index.php)
is \$2,524, and in acadenmic year 2020 - 2021 [its tuition is](https://www.collegetuitioncompare.com/edu/231624/william-mary/tuition/#:~:text=For%20the%20academic%20year%202019,out%2Dof%2Dstate%20students.)
\$48,491.

2. **Yale University**'s [tuition in 1970](https://www.nytimes.com/1969/07/13/archives/yale-tuition-and-fees-rise-to-3900-starting-in-1970.html)
is \$3,900, and in acadenmic year 2020 - 2021 [its tuition is](https://student-accounts.yale.edu/tuition-and-fees.)
\$57,700.

3. **University of PePennsylvania**'s [tuition in 1970](https://archives.upenn.edu/exhibits/penn-history/tuition/tuition-1970-1979)
is \$2,350, and in acadenmic year 2020 - 2021 [its tuition is](https://www.collegetuitioncompare.com/edu/215062/university-of-pennsylvania/tuition/#:~:text=For%20the%20academic%20year%202019,year%202020%2D2021%20is%20%2460%2C042.)
\$60,042.

4. **University of Delaware**'s [tuition in 1970](https://nces.ed.gov/programs/digest/d07/tables/dt07_320.asp)
is \$2,275, and in acadenmic year 2020 - 2021 [its tuition is](https://www.collegetuitioncompare.com/edu/130943/university-of-delaware/tuition/#:~:text=For%20the%20academic%20year%202019,out%2Dof%2Dstate%20students.)
\$35,710.

5. **Boston University**'s [tuition in 1970](https://www.nytimes.com/1970/08/13/archives/boston-u-raises-tuition.html)
is \$2,090, and in acadenmic year 2020 - 2021 [its tuition is](https://www.bu.edu/admissions/tuition-aid/tuition/)
\$56,854.

In [ ]:
P = np.array([2524 , 3900, 2350, 2275, 2090])
V = np.array([48491, 57700, 60042, 35710, 56854])
t = 2020-1970

In [ ]:
r = np.log(V/P)/t
r

array([0.05911067, 0.05388561, 0.06481258, 0.05506901, 0.06606645])

In [ ]:
from astropy.table import Table

ModuleNotFoundError: No module named 'astropy'

In [ ]:
data = {'School Name': np.array(["College of William & Mary", "Yale University",
                                 "University of Pennsylvania", "University of Delaware", "Boston University"]),
       '1970': P,
       '2020': V,
       'r(%)': np.round(r*100, decimals=2)}
Table(data)

NameError: name 'Table' is not defined

From the table above, we can see that the schools above do have similar rate of increase. College of William & Mary, Yale University, University of Pennsylvania, and University of Delaware all have rates of return less than that of Harvard; while Boston University has a rate of increase as high as 6.61%.

## Question 4

Use Python to display the day of the week each group member was born on, e.g. Monday.

Recall, you can use Python to calculate the number of days since a date. For example, the number of days since you were born. Try this, then determine, among your group members, what is the minimum and the max number of days?

### Answer to Q4

In [ ]:
import datetime

In [ ]:
f"Katherine was born on a {datetime.date(2000,4,21).strftime('%A')}"

'Katherine was born on a Friday'

In [ ]:
d0 = datetime.date (2021,2,10)
d1 = datetime.date (2000,4,21)
d2 = d0-d1
f"The number of days since Katherine was born is {d2.days}"

'The number of days since Katherine was born is 7600'

In [ ]:
f"Teresa was born on a {datetime.date(1999,12,6).strftime('%A')}"

'Teresa was born on a Monday'

In [ ]:
d0 = datetime.date (2021,2,10)
d1 = datetime.date (1999,12,6)
d2 = d0-d1
f"The number of days since Teresa was born is {d2.days}"

'The number of days since Teresa was born is 7737'

In [ ]:
f"Dylan was born on a {datetime.date(2000,3,6).strftime('%A')}"

'Dylan was born on a Monday'

In [ ]:
d0 = datetime.date (2021,2,10)
d1 = datetime.date (2000,3,6)
d2 = d0-d1
f"The number of days since Dylan was born is {d2.days}"

'The number of days since Dylan was born is 7646'

In [ ]:
f"Howard was born on a {datetime.date(2000,4,1).strftime('%A')}"

'Howard was born on a Saturday'

In [ ]:
d0 = datetime.date (2021,2,10)
d1 = datetime.date (2000,4,1)
d2 = d1-d0
f"The number of days since Howard was born is {d2.days}"

'The number of days since Howard was born is -7620'

In [ ]:
f"Shirley was born on a {datetime.date(2000,4,11).strftime('%A')}"

'Shirley was born on a Tuesday'

In [ ]:
d0 = datetime.date (2021,2,10)
d1 = datetime.date (2000,4,11)
d2 = d0-d1
f"The number of days since Shirley was born is {d2.days}"

'The number of days since Shirley was born is 7610'

In [ ]:
f"In our group, the maximum number of days is 7737 and the minimum number of days is 7600."

'In our group, the maximum number of days is 7737 and the minimum number of days is 7600.'

## Question 5
### Buying a house
Houses are expensive. Either many years of saved income or a loan are necessary to purchase a house.

By making calculations based around a simple model, in this problem you will explore the influence that the interest rate on mortgages (i.e. home loans) has on home prices.

#### Variables
 We will denote the interest rate on mortgages with the python variable `rate`, the purchase price of the home with the variable `purchase_price`, the amount of yearly spending/saving that a buyer can afford with the variable `house_spend`, and the amount of property taxes with the `prop_tax=(0.01)*purchase price` (which is approximately correct for Georgia).

In [ ]:
#@title Interest rate on 30 year mortgage (e.g. if 3%, enter 3)
percentage =  2#@param {type:"number"}
rate = percentage/100



#### Model
The specifics of loans for home buying vary greatly from one country to the next. For simplicity, we will base this model around home buying in the United States. Similarly, we will assume that the income of the home buyer is the [median income in the US](https://fred.stlouisfed.org/series/MEHOINUSA672N), $63,179, and that the amount `house_spend` is the [maximum usually suggested](https://www.forbes.com/sites/forbesfinancecouncil/2020/04/10/determining-what-percent-of-your-income-you-can-afford-to-spend-on-your-home/#544cda8737b0), namely 1/4 of gross income. Hence the variable `house_spend` we will fix as follows.

In [ ]:
house_spend=63179/4

### Extreme Buyer Profiles
Consider the following two extremes in the profiles of home buyers.  

#### Saver profile
The *saver* insists on buying a house in cash, without a loan. Note, interest rates will impact the saver, as you should assume they put the money they are saving towards a house purchase into a safe liquid investment that earns interest. For example, 10 year US treasuries. For simplicity, you may assume that this interest rate is the same as the rate `r` on mortgages. In reality it is lower, but they are strongly correlated.

#### Renter profile
The *renter* profile insists on buying a house with as little cash as possible. For example, they may be attempting *interest rate arbitrage*, where one invests whatever cash they have in investments which they hope will have a higher rate of return over the liftime of the home loan than the interest rate `rate` on the home loan. Or, they simply may not have the cash to spend. 
Typically, to avoid additional fees, it is necessary to make a down payment of 20% of the purchase price of the home, while the minimum down payment allowed is 5%. The loan term is most often 30 years, meaning the amount borrowed is paid back in full over 30 years, although 15 and 10 are also used by some buyers to minimize the amount paid in interest. Since the renter profile is taking borrowing to the extremes, we will assume they use a 30 year loan term.

For simplicity, we will assume in the calculations we make below that the renter profile puts 0% down towards the purchase price and borrows the purchase price at the interest rate `rate`.


#### Example calculations
Let's look at two examples to get you started on the exercise.

#### Example 1
Let's start by calculating the price the *saver profile* can afford to pay for a house if they save for 10 years. We will assume they start with 0 dollars and make yearly contributions into a savings account which pays a rate of interest `rate`. A formula for considering the effect of interest on these contributions can be found [here](http://www.moneychimp.com/articles/finworks/fmbasinv.htm). We use it below.

In [ ]:
time = 10 # In years

In [ ]:
saver_house_price =  house_spend*( ((1 + rate)**time - 1) / rate )

In [ ]:
f"After 10 years, the saver profile can afford to buy a house in cash with a purchase price of ${round(saver_house_price,0)}"

'After 10 years, the saver profile can afford to buy a house in cash with a purchase price of $172948.0'

#### Example 2
Next, let's calculate what the renter profile can afford. Recall, we will assume they are borrowing the full purchase price. So given they have `house_spend` to spend on their mortgage payment (interest and principle), what purchase price do we get?

Mortgages are paid monthly, hence the interest updates monthly. So for this calculation, we need to divide the `house_spend` by 12 to get the montly payment they can afford.

In [ ]:
affordable_monthly_payment = house_spend/12
affordable_monthly_payment

1316.2291666666667

The following formula can be obtained from the one found [here](https://www.mtgprofessor.com/formulas.htm) using algebra. The variables it uses are the loan term of `n` months at a monthly interest rate of `c`. If the quoted rate is 6%, for example, `c` is `.06/12` or `.005`.

In [ ]:
c=rate/12 # monthly interest rate
n = 12*30 # number of months in 30 years

In [ ]:
renter_house_price = affordable_monthly_payment/( (c*(1 + c)**n)/((1 + c)**n - 1))

In [ ]:
f"The renter profile can afford to buy a house with a purchase price of ${round(renter_house_price,0)}"

'The renter profile can afford to buy a house with a purchase price of $356104.0'



#### Tasks
Use the python code we presented to answer the following questions.

1. How many years will it take for the saver profile buyer to save enough to purchase the \$312,196 home that the renter profile can afford? Choose an interest rate (e.g. 2%) and give citations for any interest rate figures you use. 
2. Calculate what how many years the saver profile needs to save to be able to buy a house which is priced at the [median price for homes in Atlanta](https://www.zillow.com/atlanta-ga/home-values/).
3. What if the interest rate is 2% instead of 3%, or 3% instead of 2%? What if it is 10% as it was in the 1980's? Repeat the calculation in the previous question with these new interest rates. 
4. Suppose that a house is currently on the market with an asking price of \$725000 when the interest rate is 3%. Calculate how large `house_spend` would need to be for the renter profile buyer to be able to purchase this house.
5. Suppose interest rates suddenly climb from 3 up to 4%. Redo the previous calculation to see what `house_spend` needs to be under this new interest rate.
6. Suppose that suddenly interest rates drop to 2% from 4%. What can the renter afford to pay now Should the home sellers raise the asking price from \$725000 to a higher number?  

*Bonus question (1 point)*: When, historically, were the least years required for the saver profile, with a median income for the time, to buy a median priced home? When, historically, was the renter profile able to purchase the most expensive home, assuming the monthly house spend they are making is based on median income for the time as we did in our model.

### Answer to Q5

**The national average interest rate (Annual Percentage Yield) for savings accounts is 0.07 percent for the week of Jan. 27, 2021,  according to Bankrateâ€™s weekly survey of institutions ([ref](https://www.bankrate.com/banking/savings/average-savings-interest-rates/)).**

In [ ]:
#1

In [ ]:
rent_profile_afford = 312196
rate2021_perc = 0.07
rate2021 = rate2021_perc/100
f"The price that the rent profile can afford is ${round(rent_profile_afford,0)}, and the interest rate is {rate2021_perc}%"

'The price that the rent profile can afford is $312196, and the interest rate is 0.07%'

In [ ]:
time_in_year = np.log((rent_profile_afford*rate2021)/house_spend+1)/np.log(1+rate2021)
f"It will take around {round(time_in_year, 1)} years for the saver profile buyer to save enough to purchase the ${rent_profile_afford} home. "

'It will take around 19.6 years for the saver profile buyer to save enough to purchase the $312196 home. '

It will take around 19.6 years for the saver profile buyer to save enough to purchase the $312,196 home.

In [ ]:
#2

The typical home value of homes in Atlanta is $308,663 ([ref](https://www.zillow.com/atlanta-ga/home-values/)).

In [ ]:
median_price_atlanta = 308663

In [ ]:
time_in_year = np.log((median_price_atlanta*rate2021)/house_spend+1)/np.log(1+rate2021)
f"It will take around {round(time_in_year, 1)} years for the saver profile buyer to save enough to purchase a median-priced (${median_price_atlanta}) home at Atlanta. "

'It will take around 19.4 years for the saver profile buyer to save enough to purchase a median-priced ($308663) home at Atlanta. '

In [ ]:
#3

In [ ]:
rate_2 = 2/100
rate_3 = 3/100
rate_10 = 10/100

In [ ]:
time_in_year = np.log((rent_profile_afford*rate_2)/house_spend+1)/np.log(1+rate_2)
f"If the interest rate is {round(rate_2*100)}%, it will take around {round(time_in_year, 1)} years for the saver profile buyer to save enough to purchase the ${rent_profile_afford} home. "

'If the interest rate is 2%, it will take around 16.8 years for the saver profile buyer to save enough to purchase the $312196 home. '

In [ ]:
time_in_year = np.log((rent_profile_afford*rate_3)/house_spend+1)/np.log(1+rate_3)
f"If the interest rate is {round(rate_3*100)}%, it will take around {round(time_in_year, 1)} years for the saver profile buyer to save enough to purchase the ${rent_profile_afford} home. "

'If the interest rate is 3%, it will take around 15.8 years for the saver profile buyer to save enough to purchase the $312196 home. '

In [ ]:
time_in_year = np.log((rent_profile_afford*rate_10)/house_spend+1)/np.log(1+rate_10)
f"If the interest rate is {round(rate_10*100)}%, it will take around {round(time_in_year, 1)} years for the saver profile buyer to save enough to purchase the ${rent_profile_afford} home. "

'If the interest rate is 10%, it will take around 11.4 years for the saver profile buyer to save enough to purchase the $312196 home. '

In [ ]:
time_in_year = np.log((median_price_atlanta*rate_2)/house_spend+1)/np.log(1+rate_2)
f"If the interest  is {round(rate_2*100)}%, it will take around {round(time_in_year, 1)} years for the saver profile buyer to save enough to purchase a median-priced (${median_price_atlanta}) home at Atlanta. "

'If the interest  is 2%, it will take around 16.7 years for the saver profile buyer to save enough to purchase a median-priced ($308663) home at Atlanta. '

In [ ]:
time_in_year = np.log((median_price_atlanta*rate_3)/house_spend+1)/np.log(1+rate_3)
f"If the interest  is {round(rate_3*100)}%, it will take around {round(time_in_year, 1)} years for the saver profile buyer to save enough to purchase a median-priced (${median_price_atlanta}) home at Atlanta. "

'If the interest  is 3%, it will take around 15.6 years for the saver profile buyer to save enough to purchase a median-priced ($308663) home at Atlanta. '

In [ ]:
time_in_year = np.log((median_price_atlanta*rate_10)/house_spend+1)/np.log(1+rate_10)
f"If the interest  is {round(rate_10*100)}%, it will take around {round(time_in_year, 1)} years for the saver profile buyer to save enough to purchase a median-priced (${median_price_atlanta}) home at Atlanta. "

'If the interest  is 10%, it will take around 11.4 years for the saver profile buyer to save enough to purchase a median-priced ($308663) home at Atlanta. '

In [ ]:
#4

In [ ]:
asking_price = 725000
rate_3 = 3/100
rate_3_monthly = rate_3/12
n = 12 * 30
house_spend_4 = asking_price * ( (rate_3_monthly*(1 + rate_3_monthly)**n)/((1 + rate_3_monthly)**n - 1)) *12 
f"house_spend would need to be {round(house_spend_4)} for the renter profile buyer to be able to purchase this house. "

'house_spend would need to be 36680 for the renter profile buyer to be able to purchase this house. '

In [ ]:
#5

In [ ]:
rate_4 = 4/100
rate_4_monthly = rate_4/12
house_spend_5 = asking_price * ( (rate_4_monthly*(1 + rate_4_monthly)**n)/((1 + rate_4_monthly)**n - 1)) *12 
f"If the interest rate is 4%, then house_spend would need to be {round(house_spend_5)} for the renter profile buyer to be able to purchase this house. "

'If the interest rate is 4%, then house_spend would need to be 41535 for the renter profile buyer to be able to purchase this house. '

In [ ]:
#6

In [ ]:
rate_2 = 2/100
rate_2_monthly = rate_2/12
#use the house_spend value in #5
affordable_monthly_payment_6 = house_spend_5/12
renter_afford_6 = affordable_monthly_payment_6/((rate_2_monthly*(1+rate_2_monthly)**n)/((1+rate_2_monthly)**n-1))
f"If the interest rate drops to 2%, with the same house spend in #5, the renter profile buyer can afford a house with a price of ${round(renter_afford_6)}. "

'If the interest rate drops to 2%, with the same house spend in #5, the renter profile buyer can afford a house with a price of $936439. '

In this case, home sellers should raise the asking price from `$725000` to a higher number `$936439`.

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=34182c1e-ced2-433c-9676-54ec654bbd88' target="_blank">
<img style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>